config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] 
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

 get 'tops/index' => 'tops#index'
 
 get 'situations/index' => 'situations#index'
 get 'tweets/index' => 'tweets#index'
 

  resources :perfumes
  root 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user  

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy
    
     #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

  mount_uploader :image, ImageUploader
  
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         has_many :comments, dependent: :destroy
         
         has_many :tweets, dependent: :destroy 
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
         
         mount_uploader :image, ImageUploader
         
         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
      
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)
      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
        
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

    def index
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets = Tweet.all
      else
        #部分検索
        @tweets = Tweet.where("spot LIKE ? ",'%' + params[:search] + '%')
      end

      if params[:tag_ids]
        @tweets = []
        params[:tag_ids].each do |key, value|      
          @tweets += Tag.find_by(name: key).tweets if value == "1"
        end
        @tweets.uniq!
      end

      if params[:tag]
        Tag.create(name: params[:tag])
      end

      @tweets = @tweets.page(params[:page]).per(15)
  
    end

    def new
        @tweet = Tweet.new
      end

      def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id 

        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:image, :about, :spot, :title, :spot2,  :spot3, tag_ids: [])
      end

      
class MapsController < ApplicationController
  def index
  end
end

end


def index
  @tweets = Tweet.all
  if params[:search] == nil
    @tweets= Tweet.all
  elsif params[:search] == ''
    @tweets= Tweet.all
  elsif params[:search] == nil
    @tweet = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag2.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag3.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag4.find(params[:tag_id]).tweets : Tweet.all
  elsif params[:search] == ''
    @tweet = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag2.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag3.find(params[:tag_id]).tweets : Tweet.all
    @tweet = params[:tag_id].present? ? Tag4.find(params[:tag_id]).tweets : Tweet.all
  elsif params[:search].present?
    @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%')
  else
    @tweets = Tweet.where("name LIKE ? ",'%' + params[:search] + '%')
  end
end

def index
  @tweets = Tweet.all
  search = params[:search]
  @tweets = @tweets.joins(:user).where("name LIKE ?", "%#{search}%") if search.present?
  if params[:tag_ids]
    @tweets = []
    params[:tag_ids].each do |key, value|
      @tweets += Tag.find_by(name: key).tweets if value == "1"
    end
    @tweets.uniq!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/situation_helper.rb
module SituationHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </body>
    

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
                </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
                    </div>

                    <div class="col-12">
                        <p>Question4. 大切にしたいのは…</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
                    </div>
                    <div class="col-6">
                        <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
                    </div>
                </div>
            </div>
            <div class="sindanbotan">
                <%= f.submit "post" %>
            </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
            <h5>診断結果</h5>
            <p>あなたにおすすめの香りは…</p>
        </div>
        <div class="tweet-container">
            <div class="tweet">
                <% if @perfume.question == "1111" %>
                <h6>レモン</h6>
                <p>柑橘系の代表的な原料</p>
                <p>清涼感があり、爽やかな印象</p>

                <% elsif @perfume.question == "1112" %>
                <h6>シトラス</h6>
                <p>オレンジに似た柑橘系の果物</p>
                <p>リラックス効果がある</p>

                <% elsif @perfume.question == "1121" %>
                <h6>ローズ</h6>
                <p>華やかで上品な香り</p>
                <p>ストレスを緩和してくれる効果がある</p>

                <% elsif @perfume.question == "1122" %>
                <h6>ラベンダー</h6>
                <p>優しく女性らしい香り</p>
                <p>気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "1211" %>
                <h6>ジャスミン</h6>
                <p>爽やかなのに官能的な香り</p>
                <p>幸福感を得やすい</p>
                <% elsif @perfume.question == "1212" %>
                <h6>ピーチ</h6>
                <p>フレッシュで優しい香り</p>
                <p>アンチエイジングにも最適</p>

                <% elsif @perfume.question == "1221" %>
                <h6>アップル</h6>
                <p>特徴的で甘い香り</p>
                <p>万人受けしやすい</p>

                <% elsif @perfume.question == "1222" %>
                <h6>ユーカリ</h6>
                <p>しっかりとした優しい香り</p>
                <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "2111" %>
                <h6>ローズマリー</h6>
                <p>きりりとした強めの香りが特徴的</p>
                <p>美容効果が高い</p>

                <% elsif @perfume.question == "2112" %>
                <h6>ベルガモット</h6>
                <p>柑橘系の果実</p>
                <p>甘くてフレッシュな、万能な香料</p>

                <% elsif @perfume.question == "2121" %>
                <h6>ムスク</h6>
                <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
                <p>官能的で重い香り</p>

                <% elsif @perfume.question == "2122" %>
                <h6>アンバー</h6>
                <p>マッコウクジラの結石から抽出した香料</p>
                <p>魅惑的で色気のある香り</p>
                <% elsif @perfume.question == "2211" %>
                <h6>シナモン</h6>
                <p>甘いスパイスの香り</p>
                <p>香水のアクセントとしてよく使われる</p>

                <% elsif @perfume.question == "2212" %>
                <h6>バニラ</h6>
                <p>甘くて官能的な香り</p>
                <p>上品で年齢を問わず人気が高い</p>

                <% elsif @perfume.question == "2221" %>
                <h6>イランイラン</h6>
                <p>色気のある濃厚で甘い香り</p>
                <p>恋愛に効果があり</p>

                <% elsif @perfume.question == "2222" %>
                <h6>サンダルウッド</h6>
                <p>お香としてよく使われる白檀の香り</p>
                <p>集中力を高める効果もあり</p>

                <% end %>

        </div>

        <%= link_to "飲食店一覧に戻る", tweets_path %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :spot, :size => 140 %> 
    <%= f.text_field :about, :size => 140 %> 
    <%= f.text_field :spot2, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<h1>おすすめ飲食店</h1>
<h3>一覧ページ</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '飲食店名で検索する'  %>
<% end %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag 'タグで検索する' %>
<% end %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<%= link_to "新規投稿へ", new_tweet_path %>
<%= link_to "診断へ", new_perfume_path %>



<%= page_entries_info @tweets %>
<%= paginate @tweets %>

<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.user.email %> 
      <%= t.spot %>
      <%= t.title %>

      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>

      <% t.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>

     

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>

<% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "詳細", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %> 
    <% end %>
     
    </div>
  <% end %>

  <h2>gmap</h2>

  <input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display">何かが表示される、、、、！</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}


function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4uKsqry7TzUAhDrxBWt3L46mBcgsHjIw&callback=initMap" async defer></script>

</div>

app/views/tweets/new.html.erb
<h1>おすすめ飲食店の紹介</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>

  <div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
  <% end %>
</div>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 30 %>
  </div>
  
    <div class="field">
    <%= f.label :飲食店名 %>
    <%= f.text_field :spot, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
  <%= f.label :一言  %>
  <%= f.text_area :about, :size => "30x2" %>
</div>

<div class="field">
<%= f.label :詳細 %>
<%= f.text_field :spot2, :size => 30 %>
</div>

<div class="field">
<%= f.label :周辺おすすめスポット %>
<%= f.text_field :spot3, :size => 30 %>
</div>

<h2>gmap</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display">何かが表示される、、、、！</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
const display = document.getElementById('display')
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

let geocoder

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4uKsqry7TzUAhDrxBWt3L46mBcgsHjIw&callback=initMap" async defer></script>

<%= f.submit "飲食店を投稿する" %>
<% end %>

<%= link_to "飲食店一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<%= image_tag 'ドラセブン１.jpg' , size:"200×200", class:"a1" %>
<%= image_tag 'ドラセブン３.jpg', size:"200×200" ,class:"a3"%>
<%= image_tag 'ドラセブン２.jpg', size:"200×200" , class:"a2"%>
<%= image_tag 'ドラセブン４.jpg', size:"200×200", class:"a4" %>
<%= image_tag 'ドラセブン５.jpg', size:"403×400", class:"a5" %>
<%= image_tag 'ドラセブン６.jpg' , size:"403×401",class:"a6" %>
<%= image_tag 'ドラセブン７.jpg', size:"200×200" ,class:"a7" %>
<%= image_tag 'ドラセブン８.jpg' , size:"200×200",class:"a8" %>
<%= image_tag 'ドラセブン９.jpg', size:"200×200", class:"a9" %>
<%= image_tag 'ドラセブン１０.jpg', size:"200×200" ,class:"a10" %>

<div class="tweet">

    <div class=spottext>
     <p><%= @tweet.spot %></p>
    </div>

    <div class=spottext2>
     <p>新宿駅西口からすぐ！旬の和の食材のイタリアンとナチュールワインのバル！！ 
      <br> フードメニューは旬に合わせて毎月変わります！
      <br>【自家製生麺のパスタ】や【窯焼きナポリピッツァ】をメインに旬の和の食材を
      <br>使ったイタリアンをお楽しみください。
      <br>大人気のロッシーニ、シラスのペペロンチーノ、窯焼きPIZZAはもちろんありながら、
      <br>和のテイストもいれた新メニューも多数登場！！
      <br>おしゃれな賑わう空間で、思わず写真を取ってしまうインスタ映え抜群な創作料理は
      <br>女子ウケ間違いなし！
      <br>バースデープレートも予約できるので誕生日のサプライズや記念日にも使えます！
      </p>
    </div/>

    <p  class=access>【住所】東京都新宿区西新宿7-11-15 ミヤコビル 1F</p>
    <p  class=phone>【お問い合わせ】050-5595-6311</p>

</div>



<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="../demo.css">
  <link rel="stylesheet" href="buttonOutline.css">
  <title>アウトラインのボタン</title>
</head>
<body>
  <a href="https://tabelog.com/tokyo/A1304/A130401/13221779/dtlmenu/" class="buttonOutline">MENU(食べログ)</a>
</body>
<body>
  <a href="https://maps.app.goo.gl/W4t4eDEohAmGrTXRA" class="buttonOutline2">MAP</a>
</body>
<body>
  <a href="https://yoyaku.toreta.in/draemonseven/#/" class="buttonOutline3">WEB予約</a>
</body>


<div class="text">
 <ul>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
   <li>DRA7</li>
 </ul>
</div>

<div class="sample02">
 <ul>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 <li>What will you eat today? </li>
 </ul>
<div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.image %>
  <%= t.about %>
  <%= t.spot %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.image %>
  <%= t.about %>
  <%= t.spot %>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>